[package]
edition = "2021"
name = "luisa_compute_backend"
version = "0.1.1-alpha.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luisa_compute_api_types = {path = "../luisa_compute_api_types", version = "0.1.1-alpha.1"}
luisa_compute_ir = {path = "../luisa_compute_ir", version = "0.1.1-alpha.1"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
libc = "0.2"
libloading = "0.8"
lazy_static = "1.4.0"
log = "0.4"
parking_lot = "0.12.1"


[features]
default = []

[build-dependencies]


[lib]
crate-type = ["rlib"]
name = "luisa_compute_backend"
