[package]
name = "luisa_compute_ir_staticlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luisa_compute_ir = { path = "../luisa_compute_ir" }

[lib]
crate-type = ["staticlib"]
name = "luisa_compute_ir_static"
