[package]
name = "luisa_compute_ir_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8"
luisa_compute_ir = { path = "../luisa_compute_ir" }